### ISSUE TITLE
Zabbix 6.4 not supported

### ISSUE THREAD

**Issue by DevNathan** [amousset/php-weathermap-zabbix-plugin#10]
The API specs changed a little bit, and the authentification is no longer possible

**Comment by amousset** [comment]
I think haven't actually used this plugin since leaving @minet! I don't see any obvious changes regarding API authentication in Zabbix docs, do you a have a more precise error?
It seems the current best way to authenticate the API requests would be to use [named tokens](https://blog.zabbix.com/simplifying-zabbix-api-workflows-with-named-zabbix-api-tokens/16653/), it shouldn't require big changes in the plugin.

**Comment by DevNathan** [comment]
Aha, @minet still uses it ! 
Yes it's a really small fix, they changed a parameter key. 
I opened #11 for zabbix 6.4 support 
But this would break the compatibility with previous version of zabbix

**Comment by amousset** [comment]
Thanks, given this parameter was deprecated for quite some time we can just rename it. Merged and made a [release](https://github.com/amousset/php-weathermap-zabbix-plugin/releases/tag/v1.1.0) including it.

**Comment by DevNathan** [comment]
Incredible, thanks a lot
